// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one
INSERT INTO idempotency_records (id, key, request, response, status_code, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key, request, response, status_code, created_at
`

type CreateIdempotencyRecordParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Key        string             `db:"key" json:"key"`
	Request    string             `db:"request" json:"request"`
	Response   string             `db:"response" json:"response"`
	StatusCode int32              `db:"status_code" json:"status_code"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, createIdempotencyRecord,
		arg.ID,
		arg.Key,
		arg.Request,
		arg.Response,
		arg.StatusCode,
		arg.CreatedAt,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Request,
		&i.Response,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyRecordByKey = `-- name: GetIdempotencyRecordByKey :one
SELECT id, key, request, response, status_code, created_at
FROM idempotency_records
WHERE key = $1
`

func (q *Queries) GetIdempotencyRecordByKey(ctx context.Context, key string) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecordByKey, key)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Request,
		&i.Response,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateIdempotencyRecord = `-- name: UpdateIdempotencyRecord :one
UPDATE idempotency_records
SET request = $2, response = $3, status_code = $4
WHERE id = $1
RETURNING id, key, request, response, status_code, created_at
`

type UpdateIdempotencyRecordParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Request    string    `db:"request" json:"request"`
	Response   string    `db:"response" json:"response"`
	StatusCode int32     `db:"status_code" json:"status_code"`
}

func (q *Queries) UpdateIdempotencyRecord(ctx context.Context, arg UpdateIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, updateIdempotencyRecord,
		arg.ID,
		arg.Request,
		arg.Response,
		arg.StatusCode,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Request,
		&i.Response,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}
