// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Key        string             `db:"key" json:"key"`
	Request    string             `db:"request" json:"request"`
	Response   string             `db:"response" json:"response"`
	StatusCode int32              `db:"status_code" json:"status_code"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxEvent struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	AggregateID uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	EventName   string             `db:"event_name" json:"event_name"`
	Payload     []byte             `db:"payload" json:"payload"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type Product struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	SellerID   uuid.UUID          `db:"seller_id" json:"seller_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	PriceCents int64              `db:"price_cents" json:"price_cents"`
	Currency   string             `db:"currency" json:"currency"`
}

type Seller struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
