// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Key        string             `db:"key" json:"key"`
	Request    string             `db:"request" json:"request"`
	Response   string             `db:"response" json:"response"`
	StatusCode int32              `db:"status_code" json:"status_code"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Product struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Price     pgtype.Numeric     `db:"price" json:"price"`
	SellerID  uuid.UUID          `db:"seller_id" json:"seller_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Seller struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
