// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_name, payload, occurred_at, published_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY occurred_at
LIMIT $1
`

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventName,
			&i.Payload,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_id, event_name, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxEventParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	AggregateID uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	EventName   string             `db:"event_name" json:"event_name"`
	Payload     []byte             `db:"payload" json:"payload"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.EventName,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events SET published_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
