// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, price, seller_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, price, seller_id, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Price     pgtype.Numeric     `db:"price" json:"price"`
	SellerID  uuid.UUID          `db:"seller_id" json:"seller_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.SellerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.SellerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT p.id, p.name, p.price, p.seller_id, p.created_at, p.updated_at,
       s.id as s_id, s.name as s_name, s.created_at as s_created_at, s.updated_at as s_updated_at
FROM products p
JOIN sellers s ON p.seller_id = s.id
WHERE p.deleted_at IS NULL AND s.deleted_at IS NULL
ORDER BY p.created_at DESC
`

type GetAllProductsRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Price      pgtype.Numeric     `db:"price" json:"price"`
	SellerID   uuid.UUID          `db:"seller_id" json:"seller_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SID        uuid.UUID          `db:"s_id" json:"s_id"`
	SName      string             `db:"s_name" json:"s_name"`
	SCreatedAt pgtype.Timestamptz `db:"s_created_at" json:"s_created_at"`
	SUpdatedAt pgtype.Timestamptz `db:"s_updated_at" json:"s_updated_at"`
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllProductsRow{}
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.SellerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SCreatedAt,
			&i.SUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT p.id, p.name, p.price, p.seller_id, p.created_at, p.updated_at,
       s.id as s_id, s.name as s_name, s.created_at as s_created_at, s.updated_at as s_updated_at
FROM products p
JOIN sellers s ON p.seller_id = s.id
WHERE p.id = $1 AND p.deleted_at IS NULL AND s.deleted_at IS NULL
`

type GetProductByIdRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Price      pgtype.Numeric     `db:"price" json:"price"`
	SellerID   uuid.UUID          `db:"seller_id" json:"seller_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SID        uuid.UUID          `db:"s_id" json:"s_id"`
	SName      string             `db:"s_name" json:"s_name"`
	SCreatedAt pgtype.Timestamptz `db:"s_created_at" json:"s_created_at"`
	SUpdatedAt pgtype.Timestamptz `db:"s_updated_at" json:"s_updated_at"`
}

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (GetProductByIdRow, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i GetProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.SellerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SID,
		&i.SName,
		&i.SCreatedAt,
		&i.SUpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products 
SET name = $2, price = $3, seller_id = $4, updated_at = $5
WHERE id = $1
`

type UpdateProductParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Price     pgtype.Numeric     `db:"price" json:"price"`
	SellerID  uuid.UUID          `db:"seller_id" json:"seller_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.SellerID,
		arg.UpdatedAt,
	)
	return err
}
