// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyRecord, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteSeller(ctx context.Context, id uuid.UUID) error
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetAllSellers(ctx context.Context) ([]GetAllSellersRow, error)
	GetIdempotencyRecordByKey(ctx context.Context, key string) (IdempotencyRecord, error)
	GetProductById(ctx context.Context, id uuid.UUID) (GetProductByIdRow, error)
	GetSellerById(ctx context.Context, id uuid.UUID) (GetSellerByIdRow, error)
	UpdateIdempotencyRecord(ctx context.Context, arg UpdateIdempotencyRecordParams) (IdempotencyRecord, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateSeller(ctx context.Context, arg UpdateSellerParams) error
}

var _ Querier = (*Queries)(nil)
