// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sellers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO sellers (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, updated_at
`

type CreateSellerParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSeller,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeller = `-- name: DeleteSeller :exec
DELETE FROM sellers WHERE id = $1
`

func (q *Queries) DeleteSeller(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeller, id)
	return err
}

const getAllSellers = `-- name: GetAllSellers :many
SELECT id, name, created_at, updated_at
FROM sellers
ORDER BY created_at DESC
`

func (q *Queries) GetAllSellers(ctx context.Context) ([]Seller, error) {
	rows, err := q.db.Query(ctx, getAllSellers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seller{}
	for rows.Next() {
		var i Seller
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellerById = `-- name: GetSellerById :one
SELECT id, name, created_at, updated_at
FROM sellers
WHERE id = $1
`

func (q *Queries) GetSellerById(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerById, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSeller = `-- name: UpdateSeller :exec
UPDATE sellers 
SET name = $2, updated_at = $3
WHERE id = $1
`

type UpdateSellerParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSeller(ctx context.Context, arg UpdateSellerParams) error {
	_, err := q.db.Exec(ctx, updateSeller, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}
